### ISSUE TITLE
KeyError after getting fortios_configuration_fact

### ISSUE THREAD

**Issue by JelleStu** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#138]
Hi,

I'm trying to get the system_global settings from my firewall with this yml file:
```

- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: get global attributes.
     fortios_configuration_fact:
        selectors:
         - selector: system_global

```

but whenever I execute the playbook I receive this error:

```
The full traceback is:
Traceback (most recent call last):
  File "/home/jelle/.ansible/tmp/ansible-local-5170x26mjo94/ansible-tmp-1634047096.7006536-59994408794309/AnsiballZ_fortios_configuration_fact.py", line 102, in <module>
    _ansiballz_main()
  File "/home/jelle/.ansible/tmp/ansible-local-5170x26mjo94/ansible-tmp-1634047096.7006536-59994408794309/AnsiballZ_fortios_configuration_fact.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/jelle/.ansible/tmp/ansible-local-5170x26mjo94/ansible-tmp-1634047096.7006536-59994408794309/AnsiballZ_fortios_configuration_fact.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_configuration_fact', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fortios_configuration_fact_payload_yz78fvfv/ansible_fortios_configuration_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_configuration_fact.py", line 4363, in <module>
  File "/tmp/ansible_fortios_configuration_fact_payload_yz78fvfv/ansible_fortios_configuration_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_configuration_fact.py", line 4339, in main
  File "/tmp/ansible_fortios_configuration_fact_payload_yz78fvfv/ansible_fortios_configuration_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_configuration_fact.py", line 3591, in fortios_configuration_fact
KeyError: 'filters'
fatal: [fortigate01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/jelle/.ansible/tmp/ansible-local-5170x26mjo94/ansible-tmp-1634047096.7006536-59994408794309/AnsiballZ_fortios_configuration_fact.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/jelle/.ansible/tmp/ansible-local-5170x26mjo94/ansible-tmp-1634047096.7006536-59994408794309/AnsiballZ_fortios_configuration_fact.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jelle/.ansible/tmp/ansible-local-5170x26mjo94/ansible-tmp-1634047096.7006536-59994408794309/AnsiballZ_fortios_configuration_fact.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_configuration_fact', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_configuration_fact_payload_yz78fvfv/ansible_fortios_configuration_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_configuration_fact.py\", line 4363, in <module>\n  File \"/tmp/ansible_fortios_configuration_fact_payload_yz78fvfv/ansible_fortios_configuration_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_configuration_fact.py\", line 4339, in main\n  File \"/tmp/ansible_fortios_configuration_fact_payload_yz78fvfv/ansible_fortios_configuration_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_configuration_fact.py\", line 3591, in fortios_configuration_fact\nKeyError: 'filters'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
I can edit the hostname but cannot get it from my firewall.

Am I doing something wrong here>=?

**Comment by JieX19** [comment]
Hi @JelleStu,

Did you use username + password or access_token to access to the fortigate? We recommend to use access_token for the authentication.

**Set up the hosts file as follows:**

[fortigates]
fortigate01 enable_log=True ansible_host=192.168.23.21

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
access_token=stgyq3yG15d1475z9qqb80kzs4gf5r **(It's generated from GUI)**

**Please try the playbook below:**
```
- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: get global attributes.
     fortios_configuration_fact:
        access_token: "{{ access_token }}"        **<-----------  It's important to include access_token here**
        selectors:
         - selector: system_global
```

**The results getting from the playbook:**
<img width="468" alt="github" src="https://user-images.githubusercontent.com/59745792/137004611-a6d0ea37-e927-4d01-8df4-d2172d07071e.PNG">

**Comment by JelleStu** [comment]
@JieX19 I resinstalled the fortios 2.1.2 and enabled the debuging inside the fortigate.

I still receive the error at the thask get global attributes.
[console-output.txt](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/files/7351327/console-output.txt)

^Console logs

**Comment by JelleStu** [comment]
@JieX19 I also tried another selector, still get the KeyError: 'Filters' error.

Changinga setting works flawless.

**Comment by JelleStu** [comment]
Yes, I now can retrieve the fact. Thanks! :)
