### ISSUE TITLE
Bug in `module_utils/fortios/comparison.py` function `is_same_ip_address` causes `list index out of range` failure

### ISSUE THREAD

**Issue by jantari** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#155]
In the latest version of the colection (2.1.3) in the function `is_same_ip_address`:

https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/blob/e404ba837430184601c78b620e3affbe1b6a667e/plugins/module_utils/fortios/comparison.py#L17-L48

there is a bug that causes it to always fail with `IndexError: list index out of range`.

Full error:

<details>

    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
    failed: [myfortigate] (item={'name': 'redacted', 'type': 'iprange', 'address': '10.0.0.1-10.0.0.254', 'comment': 'redacted'}) => changed=false
      ansible_loop_var: item
      item:
        address: 10.0.0.1-10.0.0.254
        comment: redacted
        name: redacted
        type: iprange
      module_stderr: |-
        Traceback (most recent call last):
          File "/home/jantari/.ansible/tmp/ansible-local-12133bv_9j4pe/ansible-tmp-1640700668.471477-15671-189326056774771/AnsiballZ_fortios_firewall_address.py", line 100, in <module>
            _ansiballz_main()
          File "/home/jantari/.ansible/tmp/ansible-local-12133bv_9j4pe/ansible-tmp-1640700668.471477-15671-189326056774771/AnsiballZ_fortios_firewall_address.py", line 92, in _ansiballz_main
            invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
          File "/home/jantari/.ansible/tmp/ansible-local-12133bv_9j4pe/ansible-tmp-1640700668.471477-15671-189326056774771/AnsiballZ_fortios_firewall_address.py", line 40, in invoke_module
            runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_firewall_address', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_firewall_address', _modlib_path=modlib_path),
          File "/usr/lib/python3.8/runpy.py", line 207, in run_module
            return _run_module_code(code, init_globals, run_name, mod_spec)
          File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
            _run_code(code, mod_globals, init_globals,
          File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
            exec(code, run_globals)
          File "/tmp/ansible_fortios_firewall_address_payload_jsc29i8u/ansible_fortios_firewall_address_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_firewall_address.py", line 1912, in <module>
          File "/tmp/ansible_fortios_firewall_address_payload_jsc29i8u/ansible_fortios_firewall_address_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_firewall_address.py", line 1891, in main
          File "/tmp/ansible_fortios_firewall_address_payload_jsc29i8u/ansible_fortios_firewall_address_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_firewall_address.py", line 554, in fortios_firewall
          File "/tmp/ansible_fortios_firewall_address_payload_jsc29i8u/ansible_fortios_firewall_address_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_firewall_address.py", line 512, in firewall_address
          File "/tmp/ansible_fortios_firewall_address_payload_jsc29i8u/ansible_fortios_firewall_address_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/comparison.py", line 74, in is_same_comparison
          File "/tmp/ansible_fortios_firewall_address_payload_jsc29i8u/ansible_fortios_firewall_address_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/comparison.py", line 35, in is_same_ip_address
        IndexError: list index out of range
      module_stdout: ''
      msg: |-
        MODULE FAILURE
        See stdout/stderr for the exact error
      rc: 1

</details>

The problem is that in `is_same_ip_address` on line 35 you try to access `splitted_applied_ip[0]` which causes the error,
because `splitted_applied_ip` is still set to an empty list from line 26. Lines 30-33:

https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/blob/e404ba837430184601c78b620e3affbe1b6a667e/plugins/module_utils/fortios/comparison.py#L30-L33

attempt some odd logic to split the IP address, but your average IP address does not contain a slash or space,
e.g. when I debugged this function the variable `applied_ip` had a value of `10.0.0.254` so there was never any splitting.

**Comment by JieX19** [comment]
@jantari 

Thanks for your detailed debugging info. I'm looking into the case now and will get back to you ASAP.

**Comment by JieX19** [comment]
Hi @jantari 

The error is fixed in the latest version, please try and test on 2.1.4. I will simply close the issue because it's already adrressed. Feel free to reopen it if you have any questions.
