### ISSUE TITLE
Fortios_configuration_facts and fortios_monitor_facts error with version 2.1.3 ( working in 2.1.2 )

### ISSUE THREAD

**Issue by Raimond56** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#157]
Hello,

I am running simple playbook and it works well when I install version 2.1.2, but with version 2.1.3 it gives python syntax error. Any ideas how to solve this? Has some syntax changed for 2.1.3 ?
I am running:
ansible [core 2.11.3]
python version = 3.6.9

and installing fortinet.fortios from galaxy

```
- name: Gather available fortitokens
  hosts: forti
  collections: 
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
   
  tasks:
  - name: Get multiple selectors info concurrently
    fortios_configuration_fact:
      selector: firewall_address
```

This is the error I am getting:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/rilves/.ansible/tmp/ansible-local-34303omut70i/ansible-tmp-1643182040.8580382-3437-176171573433572/AnsiballZ_fortios_configuration_fact.py", line 100, in <module>
    _ansiballz_main()
  File "/home/rilves/.ansible/tmp/ansible-local-34303omut70i/ansible-tmp-1643182040.8580382-3437-176171573433572/AnsiballZ_fortios_configuration_fact.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/rilves/.ansible/tmp/ansible-local-34303omut70i/ansible-tmp-1643182040.8580382-3437-176171573433572/AnsiballZ_fortios_configuration_fact.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 182, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/tmp/ansible_fortios_configuration_fact_payload_0g_yfC/ansible_fortios_configuration_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_configuration_fact.py", line 5076
    **selector_obj,
     ^
SyntaxError: invalid syntax
fatal: [test_host]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/rilves/.ansible/tmp/ansible-local-34303omut70i/ansible-tmp-1643182040.8580382-3437-176171573433572/AnsiballZ_fortios_configuration_fact.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/rilves/.ansible/tmp/ansible-local-34303omut70i/ansible-tmp-1643182040.8580382-3437-176171573433572/AnsiballZ_fortios_configuration_fact.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/rilves/.ansible/tmp/ansible-local-34303omut70i/ansible-tmp-1643182040.8580382-3437-176171573433572/AnsiballZ_fortios_configuration_fact.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 182, in run_module\n    mod_name, loader, code, fname = _get_module_details(mod_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 119, in _get_module_details\n    code = loader.get_code(mod_name)\n  File \"/tmp/ansible_fortios_configuration_fact_payload_0g_yfC/ansible_fortios_configuration_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_configuration_fact.py\", line 5076\n    **selector_obj,\n     ^\nSyntaxError: invalid syntax\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by Raimond56** [comment]
I did not notice that for some reason this playbook still run with python2.7 instead of 3.6.9 which is stated when issuing command ansible --version
