### ISSUE TITLE
Module `fortios_json_generic` fails in collection version >2.1.2

### ISSUE THREAD

**Issue by alex-eoi** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#169]
Hi,

at the moment I'm working on an Ansible playbook to change the admin password of a FortiGate unit using the `fortios_json_generic` module. When running the attached task using `fortinet.fortios` version 2.1.3 or 2.1.4 the task fails, but the password is changed correctly. Instead of an OK result an Exception is thrown.
Using version 2.1.2. of `fortinet.fortios` everything works as expected.

Ansible Task:
```
        - name: Change password
          fortios_json_generic:
            vdom: "{{ vdom }}"
            json_generic:
              method: 'POST'
              path: '/api/v2/monitor/system/change-password/select'
              specialparams: "vdom={{ vdom }}"
              dictbody:
                mkey: "{{ user }}"
                old_password: "{{ ansible_password }}"
                new_password: "{{ new_password }}"
          register: result
```

Exception with Version > 2.1.2:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: formatresponse() got an unexpected keyword argument 'status'
fatal: [fgt-test001]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/automation/.ansible/tmp/ansible-local-6033tpsfsds/ansible-tmp-1647605035.3059525-707-119357169173666/AnsiballZ_fortios_json_generic.py", line 100, in <module>
        _ansiballz_main()
      File "/automation/.ansible/tmp/ansible-local-6033tpsfsds/ansible-tmp-1647605035.3059525-707-119357169173666/AnsiballZ_fortios_json_generic.py", line 92, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/automation/.ansible/tmp/ansible-local-6033tpsfsds/ansible-tmp-1647605035.3059525-707-119357169173666/AnsiballZ_fortios_json_generic.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_json_generic', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_json_generic', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_fortios_json_generic_payload_xc87jgmg/ansible_fortios_json_generic_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_json_generic.py", line 390, in <module>
      File "/tmp/ansible_fortios_json_generic_payload_xc87jgmg/ansible_fortios_json_generic_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_json_generic.py", line 379, in main
      File "/tmp/ansible_fortios_json_generic_payload_xc87jgmg/ansible_fortios_json_generic_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_json_generic.py", line 339, in fortios_json
      File "/tmp/ansible_fortios_json_generic_payload_xc87jgmg/ansible_fortios_json_generic_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_json_generic.py", line 323, in json_generic
      File "/tmp/ansible_fortios_json_generic_payload_xc87jgmg/ansible_fortios_json_generic_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 673, in jsonraw
    TypeError: formatresponse() got an unexpected keyword argument 'status'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by JieX19** [comment]
@alex-eoi 

I've reproduced the error. It seems that we improved the formatresponse( ) function for all of the modules but generic_module. It will be fixed in the next release. Thank you for raising this issue with us!

**Comment by JieX19** [comment]
The bug has been fixed in the latest version, I'm gonna close this issue.
