### ISSUE TITLE
Error in fortios_system_interface module

### ISSUE THREAD

**Issue by cardosocristian** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#184]
I'm trying to use the fortios_system_interface module and when I try to use the module to insert the secondary IP, I'm getting an error when executing the playbook.

```
- collections:
  - fortinet.fortios
  connection: httpapi
  hosts: 2600f
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    vdom: root
  tasks:
  - name: Inserindo VLAN/IP no roteador
    fortios_system_interface:
      state: present
      vdom: Externa
      system_interface:
        allowaccess: "ping"
        ip: "192.168.250.1/24"
        ipv6:
          ip6_address: "2001:db8:cafe:d4d0::1/64"
          ip6_allowaccess: "ping"
        secondary_IP: "enable"
        secondaryip:
         - allowaccess: "ping"
           ip: "192.168.251/24"
        interface: ae6-ae5-spines
        name: vlan500
        role: undefined
        vlanid: 500
```

When I run the module only with the main IP I have no problems, the playbook works smoothly, the error itself only occurs when I try to use the secondary IP configuration.

Following module error at the beginning of execution still in ansible, before connecting to Fortinet:

```
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible-fortinet/.ansible/tmp/ansible-local-8212w4sk8jrr/ansible-tmp-1652964540.241031-8215-276933994318055/AnsiballZ_fortios_system_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible-fortinet/.ansible/tmp/ansible-local-8212w4sk8jrr/ansible-tmp-1652964540.241031-8215-276933994318055/AnsiballZ_fortios_system_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible-fortinet/.ansible/tmp/ansible-local-8212w4sk8jrr/ansible-tmp-1652964540.241031-8215-276933994318055/AnsiballZ_fortios_system_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py", line 13835, in <module>
  File "/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py", line 13812, in main
  File "/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 268, in check_schema_versioning
  File "/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 209, in check_schema_versioning_internal
  File "/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 196, in check_schema_versioning_internal
AssertionError
fatal: [2600f]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible-fortinet/.ansible/tmp/ansible-local-8212w4sk8jrr/ansible-tmp-1652964540.241031-8215-276933994318055/AnsiballZ_fortios_system_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ansible-fortinet/.ansible/tmp/ansible-local-8212w4sk8jrr/ansible-tmp-1652964540.241031-8215-276933994318055/AnsiballZ_fortios_system_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansible-fortinet/.ansible/tmp/ansible-local-8212w4sk8jrr/ansible-tmp-1652964540.241031-8215-276933994318055/AnsiballZ_fortios_system_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py\", line 13835, in <module>\n  File \"/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py\", line 13812, in main\n  File \"/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 268, in check_schema_versioning\n  File \"/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 209, in check_schema_versioning_internal\n  File \"/tmp/ansible_fortios_system_interface_payload_432qcc8y/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 196, in check_schema_versioning_internal\nAssertionError\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

I'm using Ansible 2.10 and python 3.8

```
$ ansible --version
ansible 2.10.15
  config file = /home/ansible-fortinet/.ansible.cfg
  configured module search path = ['/home/ansible-fortinet/.ansible/plugins/modules', '/usr/local/share/py38-ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Jan 13 2022, 01:11:54) [Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c
```

The Fortinet collection is fortinet.fortios 2.1.4

**Comment by alagoutte** [comment]
What FortiOS release ?

**Comment by cardosocristian** [comment]
Hi @alagoutte, FortiOS Version 6.4.9

**Comment by JieX19** [comment]
@cardosocristian A required param 'id' is missing in the playbook. for example, id: 1

Can you please try it with the id? I tried this module on FOS 7.0, and it works.

**Comment by JieX19** [comment]
@cardosocristian  FYI, https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.1.6/gen/fortios_system_interface.html
