### ISSUE TITLE
Error in fortios_system_sdwan

### ISSUE THREAD

**Issue by taylorjt2** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#185]
I'm trying to create a task that allows me to create health checks for SDWAN.  I have separate tasks working for creating zones and members for SDWAN, however health checks keep erroring out.  Tried a lot of different formats.  What I think should work:
```
---
- name: Configure SD-WAN health checks.
  fortinet.fortios.fortios_system_sdwan:
    vdom:  "{{ vdom }}"
    system_sdwan:
      health_check: #"{{ cfg_sdwan_healthchecks }}"
        - name: "gah_traffic_sla"
          server: "10.97.49.251"
          members: [seq_num: 1, seq_num: 2]
          recoverytime: "50"
          sla:
            - id:  "1"
              jitter_threshold: "30"
              latency_threshold: "150"
              link_cost_factor: "latency"
              packetloss_threshold: "60"
```

Results in:
```
The full traceback is:
Traceback (most recent call last):
  File "/Users/taylorjt2/.ansible/tmp/ansible-local-29818qqs6vwf3/ansible-tmp-1653512109.129674-29823-221738496152622/AnsiballZ_fortios_system_sdwan.py", line 100, in <module>
    _ansiballz_main()
  File "/Users/taylorjt2/.ansible/tmp/ansible-local-29818qqs6vwf3/ansible-tmp-1653512109.129674-29823-221738496152622/AnsiballZ_fortios_system_sdwan.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/taylorjt2/.ansible/tmp/ansible-local-29818qqs6vwf3/ansible-tmp-1653512109.129674-29823-221738496152622/AnsiballZ_fortios_system_sdwan.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_sdwan', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_sdwan', _modlib_path=modlib_path),
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_sdwan.py", line 5533, in <module>
  File "/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_sdwan.py", line 5510, in main
  File "/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 268, in check_schema_versioning
  File "/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 209, in check_schema_versioning_internal
  File "/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 196, in check_schema_versioning_internal
AssertionError
[WARNING]: Platform darwin on host 10.99.250.250 is using the discovered Python interpreter at /usr/local/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible/2.11/reference_appendices/interpreter_discovery.html for more information.
fatal: [10.99.250.250]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/local/bin/python3.9"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/taylorjt2/.ansible/tmp/ansible-local-29818qqs6vwf3/ansible-tmp-1653512109.129674-29823-221738496152622/AnsiballZ_fortios_system_sdwan.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/Users/taylorjt2/.ansible/tmp/ansible-local-29818qqs6vwf3/ansible-tmp-1653512109.129674-29823-221738496152622/AnsiballZ_fortios_system_sdwan.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/taylorjt2/.ansible/tmp/ansible-local-29818qqs6vwf3/ansible-tmp-1653512109.129674-29823-221738496152622/AnsiballZ_fortios_system_sdwan.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_sdwan', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_sdwan', _modlib_path=modlib_path),\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_sdwan.py\", line 5533, in <module>\n  File \"/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_sdwan.py\", line 5510, in main\n  File \"/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 268, in check_schema_versioning\n  File \"/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 209, in check_schema_versioning_internal\n  File \"/var/folders/25/152brr1x4yg7f3ph6ndptd3r0000gn/T/ansible_fortinet.fortios.fortios_system_sdwan_payload_p8r8_a80/ansible_fortinet.fortios.fortios_system_sdwan_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 196, in check_schema_versioning_internal\nAssertionError\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

I'm not sure if I'm doing something wrong or if there's just an error in fortios_system_sdwan with regard to health checks.

**Comment by JieX19** [comment]
@taylorjt2, I ran the same playbook and it works. May I know what FortiOS Collection version and FOS version you use? 

Use this command **ansible-galaxy collection install fortinet.fortios:2.1.6** to install the latest version. And you probably need to upgrade your FOS to 7.0 if needed.

If the error still occurs, please provide more debugging infor to us by using the commands below:
**diagnose debug enable
diagnose debug application https**

**Comment by taylorjt2** [comment]
I was able to resolve the issue, it was a list vs dictionary definition issue.  It does work.  Thanks.
