### ISSUE TITLE
fortinet.fortios 2.3.6 does not work with ansible-core 2.17.2 for backups

### ISSUE THREAD

**Issue by Akasurde** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#338]
### Summary

I tried to run ansible for fortinet using httpapi. I have configured access_token following the documentation but I got an error message said that access_token was not defined in configuration. 

Changing the method from token to username/password also yield the same result

Error message seen below

File "/tmp/ansible_fortios_monitor_fact_payload_v68501bf/ansible_fortios_monitor_fact_payload.zip/ansible/module_utils/connection.py", line 199, in rpc
ansible.module_utils.connection.ConnectionError: Requested entry (plugin_type: connection plugin: ansible_collections.ansible.netcommon.plugins.connection.httpapi setting: access_token ) was not defined in configuration.

### Issue Type

Bug Report

### Component Name

ansible [core 2.17.2]
ansible.netcommon 7.0.0
ansible.utils     5.0.0
community.general 9.1.0
community.network 5.0.3
fortinet.fortios  2.3.6

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.2]
python version = 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] (/usr/bin/python3)
jinja version = 3.1.4
libyaml = True
```

### Configuration

```console
CONFIG_FILE() = /home/x/.ansible.cfg
DEFAULT_STDOUT_CALLBACK(/home/x/.ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/x/.ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/x/.ansible.cfg) = False

ssh:
___
host_key_checking(/home/x/.ansible.cfg) = False
```

### OS / Environment

Linux ntp 5.15.0-116-generic https://github.com/ansible-collections/ansible.netcommon/issues/126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

target device Fortinet 7.0.14

### Steps to Reproduce

STEPS TO REPRODUCE
Use below inventory, groupvars and playbook

Inventory.ini

[firewall:children]
fortigate

[fortigate]
FGT-1 fortios_access_token=access_token_from_fortigate

group_vars fortigate.yml

ansible_connection: httpapi
ansible_network_os: fortinet.fortios.fortios
ansible_user: ansible
ansible_httpapi_validate_certs: no
ansible_httpapi_use_ssl: yes
ansible_httpapi_port: 443

playbook backup.yml

hosts: firewall
gather_facts: no
collections:

fortinet.fortios
tasks:

name: backup a virtual domain.
fortios_monitor_fact:
vdom: 'root'
access_token: "{{ fortios_access_token }}"
selector: 'system_config_backup'
params:
scope: 'global'
register: backupinfo

name: Save the backup information.
copy:
content: '{{ backupinfo.meta.raw }}'
dest: 'backups/{{ inventory_hostname }}.config'

### Expected Results

Able to backup fortigate through Ansible

### Actual Results

```console
File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_osvtpsom/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3228, in <module>
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_osvtpsom/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3168, in main
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_osvtpsom/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible/module_utils/connection.py", line 199, in __rpc__
    ansible.module_utils.connection.ConnectionError: Requested entry (plugin_type: connection plugin: ansible_collections.ansible.netcommon.plugins.connection.httpapi setting: access_token ) was not defined in configuration.
```

### Code of Conduct

- [ ] I agree to follow the Ansible Code of Conduct

**Comment by Akasurde** [comment]
cc @filterfilter

**Comment by Akasurde** [comment]
This is a migrated issue, please ping @filterfilter for more information.

**Comment by MaxxLiu22** [comment]
Hi @filterfilter

Sorry for the inconvenience. We do have an issue with Ansible ansible-core==2.17.2. Please upgrade to fortinet.fortios:2.3.7 and give it a try. Let me know if the issue still persists.
```
ansible-galaxy collection install fortinet.fortios:2.3.7
```

Thanks,
Maxx

**Comment by filterfilter** [comment]
Hi Maxx,

Thank you for your response.

I have tried to use fortinet.fortios 2.3.7 with the same playbook, inventory and configuration but for some reason now I am getting a time out error now.


ansible-playbook [core 2.17.2]
  config file = /home/x/.ansible.cfg
  configured module search path = ['/home/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/x/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/x/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/x/.local/bin/ansible-playbook
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
Using /home/x/.ansible.cfg as config file
setting up inventory plugins
Loading collection ansible.builtin from
host_list declined parsing /home/x/ansible/inventory as it did not pass its verify_file() method
script declined parsing /home/x/ansible/inventory as it did not pass its verify_file() method
auto declined parsing /home/x/ansible/inventory as it did not pass its verify_file() method
Parsed /home/x/ansible/inventory inventory source with ini plugin
Loading collection fortinet.fortios from /home/x/.ansible/collections/ansible_collections/fortinet/fortios
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading collection community.general from /home/x/.ansible/collections/ansible_collections/community/general
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading callback plugin community.general.yaml of type stdout, v2.0 from /home/x/.ansible/collections/ansible_collections/community/general/plugins/callback/yaml.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: backup-fortigate.yml *******************************************************************************************************************************
Positional arguments: backup-fortigate.yml
verbosity: 4
connection: ssh
become_method: sudo
tags: ('all',)
inventory: ('/home/x/ansible/inventory',)
forks: 5
1 plays in backup-fortigate.yml

PLAY [firewall] **********************************************************************************************************************************************

TASK [backup a virtual domain.] ******************************************************************************************************************************
task path: /home/x/ansible/backup-fortigate.yml:6
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /home/x/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /home/x/.ansible/collections/ansible_collections/ansible/utils
<FGT-1> attempting to start connection
<FGT-1> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /home/x/.local/bin/ansible-connection
<FGT-1> local domain socket does not exist, starting it
<FGT-1> control socket path is /home/x/.ansible/pc/93f1faa8c4
<FGT-1> Loading collection ansible.builtin from
<FGT-1> redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<FGT-1> Loading collection ansible.netcommon from /home/x/.ansible/collections/ansible_collections/ansible/netcommon
<FGT-1> Loading collection ansible.utils from /home/x/.ansible/collections/ansible_collections/ansible/utils
<FGT-1> Loading collection fortinet.fortios from /home/x/.ansible/collections/ansible_collections/fortinet/fortios
<FGT-1> local domain socket listeners started successfully
<FGT-1> loaded API plugin ansible_collections.fortinet.fortios.plugins.httpapi.fortios from path /home/x/.ansible/collections/ansible_collections/fortinet/fortios/plugins/httpapi/fortios.py for platform type fortinet.fortios.fortios
<FGT-1> Loading collection ansible.builtin from
<FGT-1> local domain socket path is /home/x/.ansible/pc/93f1faa8c4
<FGT-1> ESTABLISH LOCAL CONNECTION FOR USER: x
<FGT-1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3 `"&& mkdir "` echo /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567 `" && echo ansible-tmp-1722578241.5234115-2054698-230612770792567="` echo /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567 `" ) && sleep 0'
Using module file /home/x/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py
<FGT-1> PUT /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/tmp76_d61p1 TO /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py
<FGT-1> EXEC /bin/sh -c 'chmod u+x /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/ /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py && sleep 0'
<FGT-1> EXEC /bin/sh -c '/usr/bin/python3 /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py && sleep 0'
<FGT-1> EXEC /bin/sh -c 'rm -f -r /home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py", line 107, in <module>
    _ansiballz_main()
  File "/home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3277, in <module>
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3228, in main
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 2507, in fortios_monitor_fact
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 581, in monitor_get
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible/module_utils/connection.py", line 199, in __rpc__
ansible.module_utils.connection.ConnectionError: command timeout triggered, timeout value is 30 secs.
See the timeout setting options in the Network Debug and Troubleshooting Guide.
fatal: [FGT-1]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py", line 107, in <module>
        _ansiballz_main()
      File "/home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/x/.ansible/tmp/ansible-local-20546480v6u9ew3/ansible-tmp-1722578241.5234115-2054698-230612770792567/AnsiballZ_fortios_monitor_fact.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', _modlib_path=modlib_path),
      File "/usr/lib/python3.10/runpy.py", line 224, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3277, in <module>
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3228, in main
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 2507, in fortios_monitor_fact
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 581, in monitor_get
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_9qx2301m/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible/module_utils/connection.py", line 199, in __rpc__
    ansible.module_utils.connection.ConnectionError: command timeout triggered, timeout value is 30 secs.
    See the timeout setting options in the Network Debug and Troubleshooting Guide.
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ***************************************************************************************************************************************************
FGT-1                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


Thanks
