### ISSUE TITLE
Cannot Use Collection (ModuleNotFoundError: No module named 'ansible_collections')

### ISSUE THREAD

**Issue by forestoden** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#45]
Hi folks,

I don't know if this is an issue with this specific Ansible collection, or something we are doing wrong in our playbooks. We started using this a couple months ago, and were able to get it working. I just revisited our playbooks to make some new updates and I am now unable to run the playbook with the collection. I upgraded my computer, so I figured it was something I was doing wrong, but some of my coworkers have run into the same issue and their environments have not changed.

The task that is currently failing is:

```
- name: fortios vpn system interface
  collections:
  - fortinet.fortios
  fortios_system_interface:
    vdom: "root"
    https: "True"
    ssl_verify: False
    state: "present"
    system_interface:
      interface: "port1"
      role: "dmz"
      device_identification: "enable"
      name: "{{ interface_name }}"
      ip: "{{ vpn_interface_ip }}/32"
      allowaccess: "ping,https,ssh"
      type: "tunnel"
      tcp_mss: 1379
      remote_ip: "{{ vpn_remote_ip }}/32"
      mtu: 1427
``` 
(Note: this is with `httpapi` but originally we were using `fortiosapi` and both seem to display this issue)

When I run this I end up with an error `ModuleNotFoundError: No module named 'ansible_collections'`. Here is the `-vvv` verbose log from Ansible

```
TASK [fortigate : fortios vpn system interface] *********************************************************************************
task path: /Users/forest.oden/Projects/fortigate-ansible/roles/fortigate/tasks/vpn.yml:36
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: forest.oden
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz `"&& mkdir /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917 && echo ansible-tmp-1597090901.185857-22913-108739685461917="` echo /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917 `" ) && sleep 0'
Using module file /Users/forest.oden/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py
<localhost> PUT /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/tmp9fh773u1 TO /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/ /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 128, in _get_module_details
    spec = importlib.util.find_spec(mod_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'ansible_collections'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 201, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 134, in _get_module_details
    raise error(msg.format(mod_name, type(ex).__name__, ex)) from ex
ImportError: Error while finding module specification for 'ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface' (ModuleNotFoundError: No module named 'ansible_collections')
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py\", line 128, in _get_module_details\n    spec = importlib.util.find_spec(mod_name)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/util.py\", line 94, in find_spec\n    parent = __import__(parent_name, fromlist=['__path__'])\nModuleNotFoundError: No module named 'ansible_collections'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/forest.oden/.ansible/tmp/ansible-local-22732exgb55cz/ansible-tmp-1597090901.185857-22913-108739685461917/AnsiballZ_fortios_system_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py\", line 201, in run_module\n    mod_name, mod_spec, code = _get_module_details(mod_name)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py\", line 134, in _get_module_details\n    raise error(msg.format(mod_name, type(ex).__name__, ex)) from ex\nImportError: Error while finding module specification for 'ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface' (ModuleNotFoundError: No module named 'ansible_collections')\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

I've tried all kinds of combinations of Python and fortios collection with no success. Whats very frustrating is that Ansible _seems_ to know about this module, based on the line 

```
Using module file /Users/forest.oden/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py
```
I've opened this file, it exists and is seemingly correct.

I'm pretty stumped by this, so hoping somebody can point me in the right direction.

**Comment by chillancezen** [comment]
@forestoden 
could you dump the Ansible version by `$ansible-playbook --version`?

**Comment by forestoden** [comment]
Of course, sorry forgot to include that.

```
$ansible-playbook --version
ansible-playbook 2.9.11
  config file = None
  configured module search path = ['/Users/forest.oden/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

**Comment by mbdraks** [comment]
@forestoden 

One way to troubleshoot this is to create a new environment to test the playbook, here's one way to do it:

1. Create Dockerfile to build image:

```Dockerfile
FROM ubuntu:19.10

RUN set -x && \
    \
    echo "==> Installing python3 and dependencies..."  && \
    apt update && \
    apt install python3-pip --yes && \
    \
    echo "==> Installing Ansible..."  && \
    pip3 install ansible && \
    \
    echo "==> Installing Ansible collections..."  && \
    echo "==> specific for FortiOS 6.2..."  && \
    ansible-galaxy collection install fortinet.fortios:1.0.10 && \
    ansible-galaxy collection install fortinet.fortimanager && \

WORKDIR /ansible
```

2. Build image and start container

3. Check if you can see the docs using the full namespace

```
ansible-doc fortinet.fortios.fortios_system_interface
```

Using the above process here's the path of my module:

`/root/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py`

Keep in mind that the ansible-galaxy collection module is not the same that comes shipped with ansible, that one is found here:

```
root@fc9c76ac267b:/ansible# ansible-doc -F | grep fortios_system_interface
fortios_system_interface                                      /usr/local/lib/python3.7/dist-packages/ansible/modules/network/fortios/fortios_system_interface.py                                  
```

4. Use the full name on the task. 

Instead of using `- collections` remove that and use the task with the name `fortinet.fortios.fortios_system_interface`. Both formats have the same effect.

5. Make sure your ansible_network_os variable is set to `fortinet.fortios.fortios`. I had issues in the past using only `fortios` as it tries to call the older modules.

**Comment by forestoden** [comment]
Hi @mbdraks, all of the checks you have listed here work as expected in my normal development environment. I did not try to set up a docker dev environment because it seems like my normal one has the collection. I use the collection for a few other tasks in the same playbook, and those actually execute without issue

**Comment by chillancezen** [comment]
@mbdraks @forestoden ,
thanks Michel, Forest for the issue,

error `No module named 'ansible_collections'` usually means environment setup issue. we'd better have a clean environment.  here I used a python3 virtual env
```
#python3 -m venv AnsibleTestEnv
#source AnsibleTestEnv/bin/activate

## Install Ansible 2.9 Base
#pip3 install ansible==2.9.9
#ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/BUGTRIAGE/AnsibleTestEnv/lib/python3.6/site-packages/ansible
  executable location = /root/BUGTRIAGE/AnsibleTestEnv/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]

## Install FortiOS Ansible collection
#ansible-galaxy collection install fortinet.fortios -f
```

please also make sure your host inventory is correct https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/playbook.html

thanks,
Link

**Comment by chillancezen** [comment]
mark this issue closed.
@forestoden please feel free to reopen it if your issue persists.

thanks,
Link
